# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7946e0a7501c677f0c28ad3d8ba678952b0437153afca350c1b6283f96f8e4bd88602d3e178c6896cbe7c2b0a7f9a0913fb92e88e157f84da5812042c302a71e

test:
  secret_key_base: 11be53a1e9567e4c214497490b36cb1faf5b5d2c41fda550dbbf5d29468ecb1eb55979383b3726408b6a42c5ce89c1f57a2083dedec9f79cb9393194331e841e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
